sudo: false

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - nightly

branches:
  only:
    - master

matrix:
  fast_finish: true

install: python setup.py install

script: python setup.py test

notifications:
  email: false
